src/algotest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('algotesting.urls', namespace = "algotesting") ),
    url(r'^admin/', include(admin.site.urls)),
]

src/algotesting/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'test/$', views.TestFormView.as_view(),name='testing'),
    url(r'about/$', views.AboutView.as_view(), name='about'),
    url(r'team/$', views.TeamView.as_view(), name='team'),
    url(r'add/$', views.AddView.as_view(), name = 'add'),
    url(r'archive/$', views.ArchiveView.as_view(), name = 'archive'),
    url(r'quick_start/$', views.QuickStartView.as_view(), name='quick_start'),
    url(r'^datasetinfo/(?P<pk>\d+)$', views.DatasetInfoView.as_view(), name = 'dataset_info'),
    url(r'datasets/$', views.DatasetListView.as_view(), name = 'datasets'),
    url(r'algorithms/$', views.AlgoListView.as_view(), name = 'algorithms'),
    url(r'add_dataset/$', views.UploadDatasetFormView.as_view(), name = 'add_dataset'),
    url(r'add_algorithm/$', views.UploadAlgorithmFormView.as_view(), name = 'add_algorithm'),
    url(r'delete_algorithm/(?P<pk>\d+)$', views.AlgorithmDeleteView.as_view(), name = 'delete_algorithm'),
    url(r'update_algorithm/(?P<pk>\d+)$', views.AlgorithmUpdateView.as_view(), name = 'update_algorithm'),
    url(r'test_results/(?P<pk>\d+)/$', views.TestResult.as_view(), name='test_results'),
    url(r'delete_algo/(?P<algo_pk>\d+)/$', views.delete_algo, name='delete_algo'),
    url(r'delete_dataset/(?P<data_pk>\d+)/$', views.delete_dataset, name='delete_dataset'),
    url(r'download_algo/(?P<algo_pk>\d+)/$', views.download_algo, name='download_algo'),
    url(r'download_params/(?P<algo_pk>\d+)/$', views.download_params, name='download_params'),
    url(r'loading/$', views.LoadingView.as_view(),name='loading'),

]

if settings.DEBUG:
    urlpatterns += [url(r'uploads/(?P<path>.*)',serve, {'document_root': settings.MEDIA_ROOT})]

src/algotesting/models.py
from django.db import models
import os,shutil

upload_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),'uploads/')

class Algorithm(models.Model):
    filename = models.CharField(default='', max_length=20, unique=True)
    name = models.CharField(default='Some algorithm', max_length=20)
    description = models.TextField(blank=True)
    algorithm = models.FileField(default='',upload_to='algorithms/')
    train_parameters = models.FileField(blank=True, null=True, upload_to='algorithms/train_params/')
    @models.permalink
    def get_absolute_url(self):
        return ('algotesting:algorithms',)

class Dataset(models.Model):
    name = models.CharField(default='Dataset', max_length=50, unique=True)
    data = models.FileField(default= '', upload_to='datasets/')
    data_filenames = models.CharField(default='',max_length=300)
    description = models.TextField(blank=True)
    frequency = models.CharField(default='daily', max_length= 6, choices=[('daily', 'daily'), ('minute', 'minute')])
    columns = models.CharField(default='', max_length=100)
    date_format = models.CharField(blank=True, default="", max_length=50)
    def delete(self, *args,**kwargs):
        path = os.path.join(upload_path, 'datasets/'+self.name)
        shutil.rmtree(path,ignore_errors = True)
        super(Dataset,self).delete(*args, **kwargs)


class ExperimentResult(models.Model):
    info = models.TextField(default='')
    test_results = models.TextField(default='')
    profit = models.BooleanField()
    results_path = models.CharField(default='', max_length=100)
    def delete(self, *args,**kwargs):
        os.remove(os.path.join(upload_path, self.results_path))
        super(ExperimentResult,self).delete(*args, **kwargs)
    @models.permalink
    def get_absolute_url(self):
        return ('algotesting:test_results', [str(self.pk)])

src/algotesting/forms.py
from django import forms
from models import Dataset, Algorithm

class UploadAlgorithmFileForm(forms.ModelForm):
    class Meta:
        model = Algorithm
        fields = ['name', 'algorithm','description','train_parameters']
        widgets = {
          'algorithm': forms.FileInput(attrs={'id': 'algo1'}),
            'train_parameters': forms.FileInput(attrs={'id': 'param1'}),
            'description':forms.Textarea(attrs={'rows':4})
        }

class UploadDataFilesForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['name','data', 'description', 'frequency', 'date_format']
        widgets = {
          'data': forms.FileInput(attrs={'id': 'data'}),
            'description':forms.Textarea(attrs={'rows':4})
        }

class QuickStartForm(forms.Form):
    capital = forms.IntegerField(min_value=1000,initial=10000)
    train_size = forms.FloatField(min_value=0.0,initial=0.5)

class NameModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class NameModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class TestingForm(forms.Form):
    algorithm = NameModelChoiceField(required=True, queryset=Algorithm.objects.all(),
                widget=forms.Select(attrs={'id':'algo-select'}), empty_label=None)

    dataset = NameModelChoiceField(required=True,queryset=Dataset.objects.all().order_by('name'),
                widget=forms.Select(attrs={'id':'datasets-select'}), empty_label=None)

    capital = forms.IntegerField(min_value=1000,initial=10000)

    train_size = forms.FloatField(min_value=0.0, initial = 0.5)
    load_parameters = forms.BooleanField(required=False, label='Load')
    save_parameters = forms.BooleanField(required=False, label='Save')

    def clean(self):
        cleaned_data = super(TestingForm, self).clean()
        algorithm = cleaned_data.get("algorithm")
        train_size = cleaned_data.get("train_size")

        if algorithm == Algorithm.objects.get(filename='lines_strat.py'):
            if train_size < 0.1 or train_size >= 1:
                raise forms.ValidationError('Algorithm Lines_strat should have train_size in range [0.1,1)')
        if algorithm == Algorithm.objects.get(filename='net4.py'):
            if train_size != 3000:
                raise forms.ValidationError('Algorithm Vanilla RNN should be tested with train size = 3000')
            dataset = cleaned_data.get('dataset')
            if dataset.name != 'CUR_EUR':
                raise forms.ValidationError('Algorithm Vanilla RNN should be tested on CUR_EUR dataset')
            load_flag = cleaned_data.get('load_parameters')
            if not load_flag:
                raise forms.ValidationError('For the algorithm Vanilla RNN train parameters should be loaded')
        if algorithm == Algorithm.objects.get(filename = 'brand_new.py'):
            if train_size != 0:
                raise forms.ValidationError('Algorithm Brand New should be tested with train size = 0')
            dataset = cleaned_data.get('dataset')
            if dataset.name != 'Brand_New_Data':
                raise forms.ValidationError('Algorithm Brand New should be tested on Brand_New_Data dataset')
            load_flag = cleaned_data.get('load_parameters')
            if not load_flag:
                raise forms.ValidationError('For the algorithm Brand New train parameters should be loaded')

src/algotesting/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import TemplateView, DetailView, ListView, FormView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect,HttpResponse
from forms import QuickStartForm, UploadDataFilesForm, TestingForm, UploadAlgorithmFileForm
from models import Dataset, ExperimentResult, Algorithm
from code.sample import handle_algorithm_testing

import os, mimetypes,zipfile
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
FILES_DELIMITER = ';'
DEFAULT_DATASET = 'Default_Daily'
DEFAULT_ALGORITHM = 'user_defined.py'

class IndexView(TemplateView):
    template_name = "index.html"

class LoadingView(TemplateView):
    template_name = "loading1.html"

class AboutView(TemplateView):
    template_name = "about.html"

class TeamView(TemplateView):
    template_name = "team.html"

class AddView(TemplateView):
    template_name = "add.html"

class ArchiveView(TemplateView):
    template_name = "archive.html"

class DatasetInfoView(DetailView):
    model = Dataset
    template_name = 'algotesting/dataset_page.html'

class DatasetListView(ListView):
    template_name = 'algotesting/datasets.html'
    form_class = UploadDataFilesForm
    context_object_name = 'datasets'
    def get_queryset(self):
        return Dataset.objects.all().order_by('name')

    def get_context_data(self, **kwargs):
        context = super(DatasetListView, self).get_context_data(**kwargs)
        context['form'] = UploadDataFilesForm
        return context

class AlgoListView(ListView):
    template_name = 'algotesting/algorithms.html'
    form_class = UploadAlgorithmFileForm
    context_object_name = 'algorithms'
    paginate_by = 20
    def get_queryset(self):
        return Algorithm.objects.all()

    def get_context_data(self, **kwargs):
        context = super(AlgoListView, self).get_context_data(**kwargs)
        context['form'] = UploadAlgorithmFileForm
        return context

def download_algo(request,algo_pk):
    algo = get_object_or_404(Algorithm, id=algo_pk)
    algo_filename = algo.filename.replace('algorithms/', '')
    fileurl=algo.algorithm.url
    mimetype = mimetypes.guess_type(fileurl)
    response = HttpResponse(algo.algorithm, content_type=mimetype)
    response['Content-Disposition'] = 'attachment; filename={}'.format(algo_filename)
    return response

def download_params(request,algo_pk):
    algo = get_object_or_404(Algorithm, id=algo_pk)
    params_filename = algo.train_parameters.name.replace('algorithms/train_params/', '')
    fileurl=algo.train_parameters.url
    mimetype = mimetypes.guess_type(fileurl)
    print mimetype
    response = HttpResponse(algo.train_parameters, content_type=mimetype)
    response['Content-Disposition'] = 'attachment; filename={}'.format(params_filename)
    return response

def delete_algo(request, algo_pk):
    algo = get_object_or_404(Algorithm, id=algo_pk)
    if algo:
        Algorithm.objects.get(pk=algo_pk).delete()
    return HttpResponseRedirect(reverse("algotesting:algorithms"))

def delete_dataset(request, data_pk):
    dataset = get_object_or_404(Dataset, id=data_pk)
    if dataset:
        Dataset.objects.get(pk=data_pk).delete()
    return HttpResponseRedirect(reverse("algotesting:datasets"))

class AlgorithmDeleteView(DeleteView):
    model = Algorithm
    template_name = "algotesting/delete_algorithm.html"
    def get_success_url(self):
        return reverse('algotesting:algorithms')

class AlgorithmUpdateView(UpdateView):
    model = Algorithm
    form_class = UploadAlgorithmFileForm
    template_name = "algotesting/update_algorithm.html"
    def form_valid(self, form):
        d = form.save(commit=False)
        d.save()
        d.filename= d.algorithm.name.replace('algorithms/','')
        d.save()
        return super(AlgorithmUpdateView, self).form_valid(form)

class UploadDatasetFormView(FormView):
    form_class = UploadDataFilesForm
    template_name = "algotesting/upload_dataset.html"
    def form_valid(self, form):
        d = form.save(commit=True)
        filepath = os.path.join(BASE_DIR,'uploads/'+d.data.name)
        dir_path = os.path.join(BASE_DIR,'uploads/datasets/'+d.name)
        os.mkdir(dir_path)
        if filepath.endswith('.zip'):
            ## Dealing with zip archive
            archive = zipfile.ZipFile(filepath)
            d.data_filenames = FILES_DELIMITER.join(archive.namelist())
            archive.extractall(path=dir_path)
            os.remove(filepath)
        else:
            file = form.cleaned_data['data']
            for file_line in file:
                d.columns = file_line[:-1]
                break
            print os.path.join(dir_path,file.name)
            os.rename(filepath,os.path.join(dir_path,file.name))
            filename = d.data.name.replace('datasets/','')
            d.data_filenames = filename
        d.save()
        return super(UploadDatasetFormView, self).form_valid(form)
    def get_success_url(self):
        return reverse('algotesting:datasets')


class UploadAlgorithmFormView(FormView):
    form_class = UploadAlgorithmFileForm
    template_name = "algotesting/upload_algorithm.html"

    def get_context_data(self, **kwargs):
        context = super(UploadAlgorithmFormView, self).get_context_data(**kwargs)
        context['object'] = Algorithm.objects.get(filename=DEFAULT_ALGORITHM)
        return context

    def form_valid(self, form):
        d = form.save(commit=False)
        d.save()
        d.filename= d.algorithm.name.replace('algorithms/','')
        d.save()
        return super(UploadAlgorithmFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('algotesting:algorithms')


class QuickStartView(FormView):
    form_class = QuickStartForm
    template_name = "algotesting/quick_start.html"
    def form_valid(self, form):
        algorithm = Algorithm.objects.get(filename=DEFAULT_ALGORITHM)
        data = Dataset.objects.get(name=DEFAULT_DATASET)
        names = [data.name+'/'+ file_name for file_name in data.data_filenames.split(FILES_DELIMITER)]
        capital = form.cleaned_data['capital']
        train_size = form.cleaned_data['train_size']
        params = {'algorithm':algorithm.filename, 'data_filenames': names, 'frequency':data.frequency,
                      'base_capital':capital, 'parser':data.date_format, 'train_size':train_size,
                      'load_file':'', 'save_file':''}
        result,portfolio = handle_algorithm_testing(params)
        earned = portfolio.iloc[-1] - portfolio.iloc[0]
        portfolio_info = 'Earned money = {}\nMax portfolio value = {}\n' \
                         'Min portfolio value = {}\n'.format(earned,portfolio.max(),
                portfolio.min())
        info = ''

        for key, value in params.items():
            if value:
                if type(value) is list:
                    if key != 'data_filenames':
                        info += "{}:{}\n".format(key, ', '.join(map(str, value)))
                    else:
                        info += "{}:{}\n".format('datasets', ', '.join(map(lambda x: x.name,[data])))
                else:
                    info += "{}:{}\n".format(key,value)

        experiment_info = info
        profit = earned > 0
        experiment_result = ExperimentResult(info = experiment_info,
                                             test_results = portfolio_info,
                                             profit = profit,results_path = '')
        experiment_result.save()

        relative_path = 'testing/results/quick_start.pdf'
        graph_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
                                      'uploads/'+relative_path)

        result.savefig(graph_path)
        plt.close(result)

        experiment_result.results_path = relative_path
        experiment_result.save()

        return redirect(experiment_result)

class TestFormView(FormView):
    form_class = TestingForm
    template_name = "algotesting/test.html"

    def get_context_data(self, **kwargs):
        context = super(TestFormView, self).get_context_data(**kwargs)
        context['pk'] = Dataset.objects.get(name=DEFAULT_DATASET).pk
        return context

    def form_valid(self, form):
        algorithm = form.cleaned_data['algorithm']
        print 'Algorithm = {}, {}'.format(algorithm.pk, algorithm.name)
        dataset = form.cleaned_data['dataset']
        load = form.cleaned_data['load_parameters']
        save = form.cleaned_data['save_parameters']
        load_params = ''
        save_params = ''
        if load and algorithm.train_parameters:
            load_params = algorithm.train_parameters.name
        if save:
            save_params = algorithm.train_parameters.name

        names = [dataset.name+'/'+ file_name for file_name in dataset.data_filenames.split(FILES_DELIMITER)]
        frequency = dataset.frequency
        parser = dataset.date_format

        print 'Data file names = {}'.format(names)

        capital = form.cleaned_data['capital']
        train_size = form.cleaned_data['train_size']
        params = {'algorithm':algorithm.filename,'data_filenames': names, 'frequency':frequency,
                      'base_capital':capital, 'parser':parser, 'train_size':train_size,
                      'load_file':load_params, 'save_file':save_params}
        result, portfolio = handle_algorithm_testing(params)
        earned = portfolio.iloc[-1] - portfolio.iloc[0]
        portfolio_info = 'Earned money = {}\nMax portfolio value = {}\n' \
                         'Min portfolio value = {}\n'.format(earned,portfolio.max(),
                portfolio.min())
        info = ''
        for key, value in params.items():
            if value:
                if type(value) is list:
                    if key != 'data_filenames':

src/algotesting/templates/algotesting/algorithms.html
{% extends "index.html" %}
{% block main-content %}
<div class="row" style="font-size: 18px">
    <div class="col col-lg-10 col-lg-offset-1">

    {% if algorithms %}
        <div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="panel-heading"><h4>Available algorithms</h4></div>

  <!-- Table -->
  <table class="table table-striped table-condensed">
            {% for algorithm in algorithms %}
                <tr>
                    <td><a href="{% url 'algotesting:update_algorithm' algorithm.pk %}">{{ algorithm.name }}</a></td>
                </tr>
            {% endfor %}
        </table>
</div>

    </div>
{% endif %}
    </div>
{% endblock main-content %}

src/algotesting/templates/algotesting/dataset_base.html
<div class="dataset">
    <div class="container">
    <div class="row">
        <div class="col col-lg-12 centered">
            <table class="table table-striped table-bordered">
                <tr>
                <td>Dataset</td><td>{{ dataset.name }}</td>
            </tr>
            <tr>
                <td>Frequency</td><td>{{ dataset.frequency }}</td>
            </tr>
            <tr>
                <td>Features</td><td>{{ dataset.columns }}</td>
            </tr>
                {% if dataset.dateformat %}
            <tr>
                <td>Datetime format</td><td>{{ dataset.date_format }}</td>
            </tr>
                {% endif %}
        </table>
        </div>
    </div>
    </div>
</div>

src/algotesting/templates/algotesting/dataset_page.html
{% extends "index.html" %}
{% block main-content %}
{% include 'algotesting/dataset_base.html' %}
<div class="container">
    <div class="row">
        <div class="col col-lg-12 centered">
<button class="btn btn-danger" role="button" data-toggle="modal" data-target="#deleteDatasetModal">Delete</button>
    {% include "algotesting/delete_dataset_modal.html" %}
        </div>
    </div>
</div>
{% endblock main-content %}

src/algotesting/templates/algotesting/datasets.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
<div class="row" style="font-size: 16px">
    <div class="col col-lg-10 col-lg-offset-1">

    {% if datasets %}
        <div class="panel panel-success">
            <div class="panel-heading"><h4>Available datasets</h4></div>
        <table class="table">
            <tr>
                <td>Name</td><td>Frequency</td><td>Features</td><td></td>
            </tr>
            {% for dataset in datasets %}
                <tr>
                    <td><a href="{% url 'algotesting:dataset_info' dataset.pk %}">{{ dataset.name }}</a></td>
                    <td>{{ dataset.frequency }}</td>
                    <td>{{ dataset.columns }}</td>
                    <td>
                        <a href="{% url 'algotesting:delete_dataset' dataset.pk %}">
                            <i class="fa fa-trash-o"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        </div>
{% endif %}
    </div>
</div>
    </div>
{% endblock main-content %}

src/algotesting/templates/algotesting/delete_algorithm.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
        <div class="panel">
            <div class="panel-body">
        <div class="col col-lg-12 centered">
<form action="" method="post">
    {% csrf_token %}
    <h3>Are you sure you want to delete algorithm <b>{{ object.name }}</b>?</h3>
    <input type="submit" value="Confirm" class="btn btn-danger" role="button"/>
</form>
        </div>
                </div>
            </div>
        </div>
</div>
<br>
{% endblock main-content %}

src/algotesting/templates/algotesting/delete_dataset_modal.html
<div class="modal fade" id="deleteDatasetModal" style="display: none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="deleteModalLabel">Delete dataset {{ dataset.name }}</h4>
            </div>

            <div class="modal-body">
                <h4>Are you sure you want to delete dataset <b>{{ dataset.name }}</b>?</h4>
            </div>

            <div class="modal-footer centered">
                <button type="button" class="btn btn-info" data-dismiss="modal">No,cancel</button>
                <a href="{% url 'algotesting:delete_dataset' dataset.pk %}">
                    <button type="button" class="btn btn-danger">Yes, delete</button>
                </a>
            </div>
        </div>
    </div>
</div>

src/algotesting/templates/algotesting/fileupdate_form.html
<div class="form-style-6" style="max-width: 550px">
<form class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        <div class="col col-lg-4">
            {% block label %}
            <label class="control-label">{{ field.label_tag }}</label>
            {% endblock label %}
        </div>

        <div class="col col-lg-8">
        {% if field == form.algorithm %}
            <div class="download_algocode_btn">
                <a href="{% url 'algotesting:download_algo' object.pk %}">
                    <button type="button" class="btn btn-link">Download {{ object.filename }}</button>
                </a>
            </div>
            <div class="controls centered">{{ field }}</div>

            {% elif field == form.train_parameters %}
                {% if object.train_parameters %}
                    <a href="{% url 'algotesting:download_params' object.pk %}">
                        <button type="button" class="btn btn-link">Download current train parameters</button>
                    </a>
                {% endif %}
                    <div class="controls ">{{ field }}</div>
        {% else %}
            <div class="controls">{{ field }}</div>
        {% endif %}
        </div>
    </div>
    {% endfor %}

    {% block additional %}
    <div class="centered">
        <button class="btn btn-danger" role="button" data-toggle="modal" data-target="#deleteModal">Delete</button>
            {% include "algotesting/delete_algorithm_modal.html" %}
        <button type ="submit" class="btn btn-success" value="Update">Update</button>
    </div>

    <script type="text/javascript">
    $("#algo1").filestyle({
        input:false,
        buttonText:' Choose new file',
        buttonName: 'btn-default'
    });

    $("#param1").filestyle({
        input:false,
        buttonText : '  Choose parameters',
        buttonName: 'btn-default'
    });
</script>
    {% endblock additional %}
</form>
</div>

src/algotesting/templates/algotesting/form_base.html
<div class="form-style-6" style="max-width:500px">
    {% block popoverscript %}
    {% endblock popoverscript %}
<form id="gds_form" class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}

    <div class="form-errors">
    {% if form.errors %}
        <p style="background-color: #ffffff; color:#000;">There are some errors in your settings:</p>
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-error" style="background-color: #d43f3a">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-error" style="background-color: #d43f3a">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    </div>

    {% for field in form %}
    <div class="form-group">
        <div class="col col-lg-4">
            {% block label %}
            <label class="control-label">{{ field.label_tag }}</label>
            {% endblock label %}
        </div>

        <div class="col col-lg-8">
            {% block field %}
            <div class="controls ">{{ field }}</div>
            {% endblock field %}
        </div>
    </div>
    {% endfor %}
    {% block button %}
    {% endblock button %}
    {% block additional %}
    {% endblock additional %}
</form>
</div>

src/algotesting/templates/algotesting/quick_start.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
	    		<div class="col-lg-12 centered">
	    			<h2>Welcome to the quick tutorial!</h2>
	    		</div>
		        {% include 'algotesting/test_form.html' %}
    </div>
</div>
{% endblock main-content %}

src/algotesting/templates/algotesting/test.html
{% extends "index.html" %}
{% block main-content %}
<div class="container">
    <div class="row">
	    		<div class="col-lg-12 centered">
	    			<h3>Welcome to the Frontopolar testing system!</h3>
	    		</div>
	</div>
	{% include 'algotesting/test_form.html' %}
</div>
{% endblock main-content %}

src/algotesting/templates/algotesting/test_results.html
{% extends "index.html" %}
{% block main-content %}
<script type="text/javascript">
    $(function () {
        ("#report").popover()
   });
 </script>

<div class="container">
<div class="row">

    <div class="col col-lg-6">
    <div class="panel-group">
         <div class="panel">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a data-toggle="collapse" href="#collapse_params"><h4>Test parameters</h4></a>
                </h5>
            </div>
        <div id="collapse_params" class="panel-collapse collapse">
            <div class="panel-body" style="color:#000000">
                {{ object.info|linebreaks }}
            </div>
        </div>
    </div>
    </div>
</div>
    <div class="col col-lg-6">
       <div class="panel-group">
         <div class="panel">
            <div class="panel-heading">
                <h5 class="panel-title">
                    <a data-toggle="collapse" href="#collapse_results">
                        <h4>Test results</h4>
                    </a>
                </h5>
            </div>
        <div id="collapse_results" class="panel-collapse collapse">
            <div class="panel-body" style="color:#000000">
                {{ object.test_results|linebreaks }}
            </div>
        </div>
    </div>
    </div>
    </div>
</div>
    <br>
<div class="row">
    <div class="col col-lg-12 centered">
        {% load static %}
        <object data-toggle="popover" data-trigger="hover" data-content='Touch' id="#report" height="500" width="90%" type="application/pdf" data="{% get_media_prefix %}{{ object.results_path  }}"></object>
    </div>

</div>
</div>
    </div>

{% endblock main-content %}

src/algotesting/templates/algotesting/update_algorithm.html
{% extends "index.html" %}
{% block main-content %}

<div class="container">
        {% include 'algotesting/fileupdate_form.html' %}
</div>
<br>
{% endblock main-content %}

src/algotesting/templates/algotesting/upload_algorithm.html
{% extends "algotesting/base_upload.html" %}

{% block fileinfo %}
<div class="row">
    <div class="col col-lg-6 col-lg-offset-3">
    <div class="panel-group">
         <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <a data-toggle="collapse" href="#collapse1"><h4>Algorithm instruction</h4></a>
                </h3>
            </div>
        <div id="collapse1" class="panel-collapse collapse">
            <div class="panel-body">
            <div class="lead">
        <h5><b>Algorithm</b> - user defined python source file which contains functions initialize, handle_data and optionally
        functions load, save and analyze</h5>
        <h5>
            <b>Initialize</b> - function for learning
        </h5>
        <h5>
            <b>Handle_data</b> - function for buying and selling and optionally for online learning
        </h5>
            <h5>
                <b>Load</b> - function which defines the way algorithm training parameters are loaded. If not specified,
                default function just pickles out result variable from train parameters file if it's uploaded
            </h5>
            <h5>
                <b>Save</b> - function which defines the way algorithm training parameters are saved. If not specified,
                default function pickles result to train parameters file if it's uploaded:
            </h5>
            <h5>
                <b>Analyze</b> - function for depicting the results of testing algorithm. It should plot everything needed
                and return figure object. Default function would plot graph of portfolio value
                (run <a href="{% url 'algotesting:quick_start' %}">Quick Start</a> for an example)
            </h5>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
{% endblock fileinfo %}