src/algotest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('algotesting.urls', namespace = "algotesting") ),
    url(r'^admin/', include(admin.site.urls)),
]

src/algotesting/urls.py
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'test/$', views.TestFormView.as_view(),name='testing'),
    url(r'about/$', views.AboutView.as_view(), name='about'),
    url(r'team/$', views.TeamView.as_view(), name='team'),
    url(r'add/$', views.AddView.as_view(), name = 'add'),
    url(r'archive/$', views.ArchiveView.as_view(), name = 'archive'),
    url(r'quick_start/$', views.QuickStartView.as_view(), name='quick_start'),
    url(r'^datasetinfo/(?P<pk>\d+)$', views.DatasetInfoView.as_view(), name = 'dataset_info'),
    url(r'datasets/$', views.DatasetListView.as_view(), name = 'datasets'),
    url(r'algorithms/$', views.AlgoListView.as_view(), name = 'algorithms'),
    url(r'add_dataset/$', views.UploadDatasetFormView.as_view(), name = 'add_dataset'),
    url(r'add_algorithm/$', views.UploadAlgorithmFormView.as_view(), name = 'add_algorithm'),
    url(r'delete_algorithm/(?P<pk>\d+)$', views.AlgorithmDeleteView.as_view(), name = 'delete_algorithm'),
    url(r'update_algorithm/(?P<pk>\d+)$', views.AlgorithmUpdateView.as_view(), name = 'update_algorithm'),
    url(r'test_results/(?P<pk>\d+)/$', views.TestResult.as_view(), name='test_results'),
    url(r'delete_algo/(?P<algo_pk>\d+)/$', views.delete_algo, name='delete_algo'),
    url(r'delete_dataset/(?P<data_pk>\d+)/$', views.delete_dataset, name='delete_dataset'),
    url(r'download_algo/(?P<algo_pk>\d+)/$', views.download_algo, name='download_algo'),
    url(r'download_params/(?P<algo_pk>\d+)/$', views.download_params, name='download_params'),
    url(r'loading/$', views.LoadingView.as_view(),name='loading'),

]

if settings.DEBUG:
    urlpatterns += [url(r'uploads/(?P<path>.*)',serve, {'document_root': settings.MEDIA_ROOT})]

src/templates/about.html
{% extends "index.html" %}
{% load staticfiles %}
{% block main-content %}



<div id="green">
    <div class="container">
			<div class="row">
				<div class="col col-lg-3 col-lg-offset-2" >
					<div><img src="{% static 'algotesting/assets/img/brain_logo.png' %}" alt="" style="display: inline-block"></div>
                </div>
                    <div class="col col-lg-7" style="text-align: center">
                        <h3>About the project:</h3>
					    <p>We explore Deep Learning application to the financial instruments</p>
                        <p>We study and create new algorithms in the area</p>
                        <p>We build a framework, in which all of this can be seen</p>
                        </div>
				</div>

			</div>
    </div>
</div>

<div class="container" style="padding-top: 20px">
    <div class="row" style="text-align: center">
        <div class="col col-lg-1"></div>
        <div class="col col-lg-10">
     <div class="panel panel-success">
         <div class="panel-heading" style="background-color: #74cfae;">
             <h3 style="color: white;font-weight: 400;">Comparison with existing frameworks</h3>
         </div>

        <div class="panel-body">
            {% include "about_table.html" %}
        </div>
        </div>
         </div>
        <div class="col col-lg-1"></div>
	</div>
</div>

{% endblock main-content %}

src/templates/about_table.html
<div class="about-table" style="padding: 10px">
	<table class="table" style="color:#555;" cellspacing="0" cellpadding="0" border="0">

            <tr>
                <td width="250"></td>
			    <td class="frontopolar"><h4><b>Frontopolar</b></h4></td>
			    <td><h4><b>Quantopian</b></h4></td>
			    <td><h4><b>Cloud9trader</b></h4></td>
			    <td><h4><b>Websim</b></h4></td>

		    </tr>
		<tr>
			<td>Ability to upload user data</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td>Ability to download a large number of files in the archive</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td>Providing information on stocks</td>
			<td class="frontopolar"><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-plus"></i></td>
		</tr>
		<tr>
			<td>Handling of minute data</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-plus"></i></td>
            <td><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td>Report generation in defined format</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td>Output error traceback</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-plus"></i></td>
		</tr>
		<tr>
			<td>Ability to change value of commission</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td><h4><b>Machine learning features</b></h4></td>
			<td class="frontopolar"></td><td></td><td></td><td></td>
		</tr>
		<tr>
			<td>Usage of Theano and Lasagne libraries</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td>Training stage</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td>Train/test data splitting</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
		<tr>
			<td>Loading previously trained model</td>
			<td class="frontopolar"><i class="fa fa-plus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
			<td><i class="fa fa-minus"></i></td>
		</tr>
</table>
</div>

src/templates/add.html
{% extends "index.html" %}
{% load staticfiles %}
{% block main-content %}

<div class="container">
		<div class="row centered mt grid">
			<h2>Upload</h2>
			<div class="mt"></div>
            <div class="col-lg-3"></div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:add_dataset' %}"><i class="fa fa-table fa-4x"></i></a>
                <h3>Upload new dataset</h3>
			</div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:add_algorithm' %}"><i class="fa fa-cogs fa-4x"></i></a>
                <h3>Upload new algorithm</h3>
			</div>
            <div class="col-lg-3"></div>
		</div>
</div>
{% endblock main-content%}

src/templates/archive.html
{% extends "index.html" %}
{% load staticfiles %}
{% block main-content %}

<div class="container">
		<div class="row centered mt grid">
			<h2>Available files</h2>
			<div class="mt"></div>
            <div class="col-lg-3"></div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:datasets' %}"><i class="fa fa-table fa-4x"></i></a>
                <h3>Datasets</h3>
			</div>
			<div class="col-lg-3">
                <a class="navbar-brand" href="{% url 'algotesting:algorithms' %}"><i class="fa fa-cogs fa-4x"></i></a>
                <h3>Algorithms</h3>
			</div>
            <div class="col-lg-3"></div>
		</div>
</div>
{% endblock main-content%}

src/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Frontopolar</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'algotesting/assets/css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'algotesting/assets/css/main.css' %}" rel="stylesheet">
    <link href="{% static 'algotesting/assets/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'algotesting/assets/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'algotesting/assets/css/bootstrap-multiselect.css' %}" rel="stylesheet">
      <script src="{% static 'algotesting/assets/js/jquery-2.2.3.min.js' %}"></script>
    <script src="{% static 'algotesting/assets/js/bootstrap-multiselect.js' %}"></script>
    <script src="{% static 'algotesting/assets/js/chart.js' %}"></script>
    <script src="{% static 'algotesting/assets/js/bootstrap-filestyle.min.js' %}"></script>

  </head>

  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <table>
            <tr>
              <td><a class="navbar-brand" href="{% url 'algotesting:index' %}"><i class="fa fa-home"></i></a></td>
              <td><a class="navbar-brand" href="{% url 'algotesting:testing' %}"><i class="fa fa-rocket"></i></a></td>
              <td><a class="navbar-brand" href="{% url 'algotesting:archive' %}"><i class="fa fa-archive"></i></a></td>
              <td><a class="navbar-brand" href="{% url 'algotesting:add' %}"><i class="fa fa-upload"></i></a></td>
            </tr>
            <tr>
              <td style="color:#555">Home</td>
              <td style="color:#555">Test</td>
              <td style="color:#555">Files</td>
              <td style="color:#555">Upload</td>
            </tr>
          </table>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
              <li class = "active"><a href = "{% url 'algotesting:quick_start' %}">Quick Start</a></li>
               <li><a href="{% url 'algotesting:about' %}">About</a></li>
              <li><a href="{% url 'algotesting:team' %}">Team</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

   <div style="padding-top: 60px;padding-bottom: 20px;">
    {% block main-content %}
	<div id="hello">
	    <div class="container">
	    	<div class="row">
	    		<div class="col-lg-8 col-lg-offset-2 centered">
	    			<h1>Frontopolar</h1>
	    			<h2>Deep Learning Framework for Trading</h2>
	    		</div><!-- /col-lg-8 -->
	    	</div><!-- /row -->
	    </div> <!-- /container -->
	</div><!-- /hello -->

    {% endblock main-content %}
    </div>

	<div id="f">
		<div class="container">
			<div class="row">
				<p>Crafted with <i class="fa fa-heart"></i> by DIHT MIPT</p>
			</div>
		</div>
	</div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'algotesting/assets/js/bootstrap.js' %}"></script>
  </body>
</html>

src/templates/loading1.html
<style>
    @import url(http://weloveiconfonts.com/api/?family=entypo);
    @import url(http://fonts.googleapis.com/css?family=Audiowide);

.animation {
  padding: 50px;
  text-align: center;
  color: white;
  text-shadow: 0 0 10px #084;
  background: radial-gradient(center,circle cover,transparent 0%, transparent 50%, rgba(0,0,0,0.2) 100%);
  background-color: darkseagreen;
}

.loading {
  font-size: 60px;
  font-family: "Audiowide";
}

.gears {
  animation: rotate1 6s linear infinite;
}

.entypo-cog {
  position: relative;
  display: block;
  padding: 0;
  margin: 0;
  font-size: 150px;
  font-family: "entypo";
}

.entypo-cog:nth-child(1) {
  animation: rotate1 3s linear infinite;
}

.entypo-cog:nth-child(2) {
  margin-top: -35px;
  transform: rotate(22.5deg);
  animation: rotate2 3s linear infinite;
}

@keyframes rotate1 {
  to { transform: rotate(360deg); }
}

@keyframes rotate2 {
  from { transform: rotate(-22.5deg) }
  to { transform: rotate(-382.5deg); }
}</style>

<div id="wait10" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
<div class="animation">
<div class="loading">
  LOADING
  <div class="gears">
    <div class="entypo-cog"></div>
    <div class="entypo-cog"></div>
  </div>
</div>
</div>
        </div>
</div>

src/templates/team.html
{% extends "index.html" %}
{% block main-content %}
{% load staticfiles %}

<div class="team">
<div class="container" >
	<div class="row">
		<h2 style="text-align: center;padding-bottom: 10px;">Meet the team:</h2>
		<div class="col col-lg-6">

  <div class="panel-group" id="accordion" >
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
			  	<img src="{% static 'algotesting/assets/img/brains_green.png' %}" height="100" style="padding-right: 10px">
			  <span style="font-size: 18px;"><b>Brand New Team</b></span>
		  </a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <div class="panel-body">
				<table class="table table-striped">
				<tr>
					<td><img src="{% static 'algotesting/assets/img/br1.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/br2.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/br3.png' %}" width="75"></td>
				</tr>
				<tr>
					<td>Першаков Николай</td>
					<td>Подкин Алексей</td>
					<td>Матушкин Александр</td>
				</tr>
				</table>
			<table class="table table-striped">
					<tr><td>Applying deep learning to the financial instruments</td></tr>
					<tr><td>Using modern methods of deep learning to build the optimal trading strategies</td></tr>
					<tr><td>Creating new algorithms</td></tr>
					<tr><td>Testing our strategy on real data</td></tr>
					</table>

		</div>
      </div>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
			  <img src="{% static 'algotesting/assets/img/graph_green.png' %}" height="100" style="padding-right: 20px">
			  <span style="font-size: 18px;"><b>Research Team</b></span>
		  </a>
        </h4>
      </div>
      <div id="collapse2" class="panel-collapse collapse">
        <div class="panel-body">
			<table class="table table-striped">
				<tr>
					<td><img src="{% static 'algotesting/assets/img/r1.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/r2.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/r3.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/r4.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/r5.png' %}" width="75"></td>
				</tr>
				<tr>
					<td>Алексеев Федор</td>
					<td>Персиянов Дмитрий</td>
					<td>Грицай Артем</td>
					<td>Медведева Анна</td>
					<td>Иванов Илья</td>
				</tr>
				</table>
			<table class="table table-striped">
<tr><td>Applying deep learning to the financial instruments</td></tr>
<tr><td>Investigating articles with new algorithms</td></tr>
<tr><td>Implementing the most promising algorithms</td></tr>
<tr><td>Improving algorithms using machine learning techniques</td></tr>
				</table>
		</div>
      </div>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
			  <img src="{% static 'algotesting/assets/img/dev_green.png' %}" height="100" style="padding-right: 20px">
			  <span style="font-size: 18px;"><b>Framework Team</b></span>
		  </a>
        </h4>
      </div>
      <div id="collapse3" class="panel-collapse collapse">
        <div class="panel-body">
			<table class="table table-striped">
				<tr>
					<td><img src="{% static 'algotesting/assets/img/f1.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/f2.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/f3.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/f4.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/f5.png' %}" width="75"></td>
				</tr>
				<tr>
					<td>Колмаков Сергей</td>
					<td>Сухуроченков Артем</td>
					<td>Сторожилова Елена</td>
					<td>Капцан Арсений</td>
					<td>Ермолаева Анастасия</td>
				</tr>
				</table>
			<table class="table table-striped">
<tr><td>Designing algorithms for api</td></tr>
<tr><td>Creating local and on-line testing tools</td></tr>
<tr><td>Helping to integrate algorithms in the testing system</td></tr>
<tr><td>Creating a website showing information about the project</td></tr>
				</table>
		</div>
      </div>
    </div>
</div></div>

		<div class="col col-lg-6">
			<div class="panel-group" id="accordion1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion1" href="#collapse4">
			  <img src="{% static 'algotesting/assets/img/mentors.png' %}" height="100" style="padding-right: 20px">
			  <span style="font-size: 18px;"><b>Mentors</b></span>
		  </a>
        </h4>
      </div>
      <div id="collapse4" class="panel-collapse collapse">
        <div class="panel-body">
			<table class="table table-striped">
				<tr>
					<td><img src="{% static 'algotesting/assets/img/m1.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/m2.png' %}" width="75"></td>

				</tr>
				<tr>
					<td>Давлетшин Азат</td>
					<td>Орлов Никита</td>
				</tr>
				<tr>
					<td>Разработчик технологического департамента компании ABBYY (группа OCR)</td>
					<td>Разработчик технологического департамента компании ABBYY (группа Image Analysis)</td>
				</tr>
				</table>
		</div>
      </div>
    </div>


    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion1" href="#collapse5">
			  <img src="{% static 'algotesting/assets/img/mentors1.png' %}" height="100" style="padding-right: 20px">
			  <span style="font-size: 18px;"><b>Scrum masters and product owners</b></span>
		  </a>
        </h4>
      </div>
      <div id="collapse5" class="panel-collapse collapse">
        <div class="panel-body">
						<table class="table table-striped">
				<tr>
					<td><img src="{% static 'algotesting/assets/img/sc1.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/sc2.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/sc3.png' %}" width="75"></td>
					<td><img src="{% static 'algotesting/assets/img/sc4.png' %}" width="75"></td>
				</tr>
							<tr>
					<td>Вяткина Анна</td>
					<td>Ичалова Диана</td>
					<td>Кочетов Николай</td>
					<td>Контуров Дмитрий</td>
				</tr>
							</table>
		</div>
      </div>
    </div>
		</div>

		</div>
  </div>
</div>

	</div>


{% endblock main-content%}